name: Build Electron App (Cross-Platform)

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - "v*"  # Runs on version tags like v1.0.0

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [win32, linux]
        include:
          - platform: win32
            os: windows-latest
          - platform: linux
            os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package Electron App
        run: |
          npx electron-packager . Coursera \
            --platform=${{ matrix.platform }} \
            --arch=x64 \
            --out=release \
            --overwrite

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Coursera-${{ matrix.platform }}
          path: release/**
